# Default Configuration
framesPerSecond: 60
forceScale: 100
levelDir: levels
levelExtension: .yaml
menuBarWidth: 120
startTime: 1500
windowHeight: 768
windowTitle: Make It Hit - {0} (FPS: {1})
windowWidth: 1024